.TH ARDENTRYST "6" "January 2011" "ardentryst 1.71"
.SH NAME
ardentryst \- Action/RPG sidescoller, focused on story and character development
.SH SYNOPSIS
.B ardentryst
.SH DESCRIPTION
\fBardentryst\fR is an action/RPG sidescoller, focused not just on fighting,
but on story, and character development. It features two playable characters
and a variety of weapons, items, armour, monsters, and beautiful level
scenery and graphics.
.SH AUTHOR
\fBardentryst\fR was written by Jordan Trudgett <jordan_trudgett@hotmail.com>
.PP
This manual page was written by Vincent Cheng <vcheng@debian.org>,
for the Debian project (and may be used by others).
